version: "3"
services:
  3m:
    image: ${SOURCE_REGISTRY:-docker.io}${SOURCE_GROUP:-/}${SOURCE_IMAGE:-docker}:${SOURCE_VERSION:-0.0.0}
    working_dir: ${WORKING_DIR:-/opt/3m}
    volumes:
      - .:${WORKING_DIR:-/opt/3m}
      - ${_DOCKER_HOME:-.docker}:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ${ENVFILE:-.env}

