name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOURCE_GROUP: '/'
  SOURCE_IMAGE: 'docker'
  SOURCE_REGISTRY: 'docker.io'
  SOURCE_VERSION: '20.10.10-dind-rootless'
  TARGET_BUILD: ${{ github.run_number }}
  TARGET_GROUP: '/whateverany'
  TARGET_IMAGE: '3m-docker'
  TARGET_REGISTRY: 'docker.pkg.github.com'
  TARGET_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TARGET_REGISTRY_USER: ${{ github.actor }}
  TARGET_VERSION: ${{ github.ref }}
  _DOCKER_HOME: '.docker'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: make build
    - name: login
      run: make login
    - name: publish
      run: make publish
    - name: logout
      run: make logout

