name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOURCE_GROUP: '/'
  SOURCE_IMAGE: 'docker'
  SOURCE_REGISTRY: 'docker.io'
  SOURCE_VERSION: '20.10.10-dind-rootless'
  TARGET_BUILD: '0'
  TARGET_GROUP: '/whateverany'
  TARGET_IMAGE: '3m-docker'
  TARGET_REGISTRY: 'github.com'
  TARGET_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TARGET_REGISTRY_USER: ${{ github.actor }}
  TARGET_VERSION: '0.0.0'
  _DOCKER_HOME: '.docker'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: make build
    - name: login
      run: make login

