name: build
on:  
  push:
    tags:
      - '*'

env:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: env
      run: |
        set -x
        grep "=" ".env.template" | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" >> "${GITHUB_ENV}"
        #
        echo "TARGET_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
        echo "TARGET_BUILD=${{ github.run_number }}" >> $GITHUB_ENV
        echo "TARGET_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        echo "TARGET_REGISTRY_USER=${{ github.actor }}" >> $GITHUB_ENV
        #
        echo "INFO: GITHUB_ENV:"
        cat "${GITHUB_ENV}"
    - name: login
      run: make login
    - name: build
      run: make build
    - name: publish
      run: make publish
    - name: logout
      run: make logout

